name: deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setting up kubectl
        uses: azure/setup-kubectl@v3
      - name: setting up kubectl context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: $\{{ secrets.KUBECONFIG }}
